### ISSUE TITLE
Request: More In-Depth config setup for NGINX

### ISSUE THREAD

**Issue by artistro08** [OFFLINE-GmbH/oc-responsive-images-plugin#60]
I've been trying for weeks to get this setup on a nginx server and I just cannot for the life of me figure out how to do so.

my questions are

 - Where exactly does the config go?
 - do i put this in my server block AND my `/etc/nginx/nginx.conf?`

Any guidance would be appreciated

**Comment by tobias-kuendig** [comment]
This goes into your `/etc/nginx/nginx.conf`

```nginx
  map $http_accept $webp_suffix {
    default   "";
    "~*webp"  ".webp";
  }
```
This goes into your `/etc/nginx/sites-enabled/your-site.conf`

```nginx
server {
    # ...
    location ~ \.(jpe?g|png)$ {
	add_header Vary Accept;
        try_files $uri$webp_suffix $uri/ @router;
    }

    location @router {
        rewrite ^(.*)$ /plugins/offline/responsiveimages/webp.php?path=$uri;
    }

```

The nginx config example came from the community. I cannot guarantee you this is working. Since the plugin uses `rosell-dk/webp-convert` under the hood, you can search for any nginx setup of any CMS that uses this library.

There is some more detailed documentation over there, you just have to change the webp.php path accordingly.
https://github.com/rosell-dk/webp-express#i-am-on-nginx-or-openresty

**Comment by artistro08** [comment]
I didn't get this working, but thank you for that. I think my setup with DigitalOcean isn't picking up on the redirects. 

Once again, thank you. Closing this for relevance
